name: Tour Guide .NET Core API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --logger trx --results-directory "TestResults"

    - name: Publish
    # Use SUccess() to run this step only if previous steps are successfull  
      if: success()
      run: dotnet publish --configuration Release --output ./publish

    - name: Publish artefacts
      # Use SUccess() to run this step only if previous steps are successfull
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: Upload artefacts
        path: ./publish

    - name: Upload dotnet test results
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-results
        path: TestResults
